import '../../shared/models/qc_report_model.dart';
import '../../shared/models/qc_checklist_answer_model.dart';
import '../../shared/models/work_location_model.dart';
import '../../shared/models/enums.dart';

final List<QCReportModel> dummyReports = [
  // 1. Tiang Besi 7M 3 Segmen (Material - Approved/Lulus)
  QCReportModel(
    id: 'QC-MAT-2026-0041',
    title: 'Tiang Besi 7M 3 Segmen',
    type: QCType.material,
    status: QCReportStatus.APPROVED,
    checkedByName: 'Yanuar Luthfi',
    checkedByNik: 'NIK-908271',
    date: DateTime.now().subtract(const Duration(days: 2)),
    siteId: 'site-1',
    siteName: 'Gudang Material Utama',
    area: 'Sektor 4 - Area Utara',
    detailLocation: 'Gudang Utama A-1',
    formCode: 'TA-FR-048-010-01',
    finalConclusion: 'Disetujui',
    workLocation: WorkLocation(
      siteName: 'Gudang Material Utama',
      area: 'Sektor 4 - Area Utara',
      segment: 'Gudang Utama A-1',
      isCustom: false,
    ),
    generalInfo: {
      'poNumber': 'PO-2026-090',
      'poDate': '2026-06-10',
      'doNumber': 'DO-889011',
      'vendorName': 'PT Wahana Logam',
      'materialId': 'MAT-B-7M-3S',
      'arrivalVolume': '1 batch',
      'samplingVolume': '5',
      'brandName': 'Pionir Besi',
      'warehouseLocation': 'Gudang Utama A-1',
      'stelVersion': 'STEL-L-017-2024 Ver.2',
      'qaExpiryDate': '2028-12-31',
      'tkdnNumber': 'TKDN-BESI-8871',
      'tkdnCertDate': '2025-01-20',
      'tkdnValue': '45.2',
    },
    checklistAnswers: [
      QCChecklistAnswer(
        itemId: 'tb73-1',
        value: 'OK',
        status: QCResultStatus.pass,
        photoPaths: ['https://images.unsplash.com/photo-1581094288338-2314dddb7ecc?auto=format&fit=crop&w=150&q=80'],
        paramName: 'Kondisi fisik luar baik/tidak cacat',
        standardText: 'OK',
      ),
      QCChecklistAnswer(
        itemId: 'tb73-2',
        value: '7010',
        status: QCResultStatus.pass,
        photoPaths: ['https://images.unsplash.com/photo-1590069261209-f8e9b8642343?auto=format&fit=crop&w=150&q=80'],
        paramName: 'Panjang total',
        standardText: '7000 ± 40 mm',
        unit: 'mm',
      ),
    ],
    photos: [],
    staffNote: 'Inspeksi material tiang besi masuk dari pabrikasi lancar. Kualitas besi sangat kokoh.',
    adminNote: 'Laporan disetujui.',
  ),

  // 2. Tiang Beton 7 Meter (Material - Approved/Lulus)
  QCReportModel(
    id: 'QC-MAT-2026-0042',
    title: 'Tiang Beton 7 Meter',
    type: QCType.material,
    status: QCReportStatus.APPROVED,
    checkedByName: 'Yanuar Luthfi',
    checkedByNik: 'NIK-908271',
    date: DateTime.now().subtract(const Duration(days: 3)),
    siteId: 'site-1',
    siteName: 'Gudang Material Utama',
    area: 'Sektor 4 - Area Utara',
    detailLocation: 'Gudang Utama A-2',
    formCode: 'TA-FR-048-010-02',
    finalConclusion: 'Disetujui',
    workLocation: WorkLocation(
      siteName: 'Gudang Material Utama',
      area: 'Sektor 4 - Area Utara',
      segment: 'Gudang Utama A-2',
      isCustom: false,
    ),
    generalInfo: {
      'poNumber': 'PO-2026-091',
      'poDate': '2026-06-11',
      'doNumber': 'DO-889012',
      'vendorName': 'PT Beton Mandiri',
      'materialId': 'MAT-BETON-7M',
      'arrivalVolume': '1 batch',
      'samplingVolume': '3',
      'brandName': 'Beton Perkasa',
      'warehouseLocation': 'Gudang Utama A-2',
      'stelVersion': 'STEL-L-018-2024',
      'qaExpiryDate': '2029-06-30',
      'tkdnNumber': 'TKDN-BETON-4411',
      'tkdnCertDate': '2025-02-15',
      'tkdnValue': '52.3',
    },
    checklistAnswers: [
      QCChecklistAnswer(
        itemId: 'tb-beton-1',
        value: 'OK',
        status: QCResultStatus.pass,
        photoPaths: ['https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=150&q=80'],
        paramName: 'Kondisi fisik luar baik',
        standardText: 'OK',
      ),
    ],
    photos: [],
    staffNote: 'Kondisi fisik beton baik dan tidak retak.',
    adminNote: 'Disetujui.',
  ),

  // 3. Tiang Galvanis 6M Tanpa Sambungan (Material - NeedFollowUp/Perlu Perbaikan)
  QCReportModel(
    id: 'QC-MAT-2026-0043',
    title: 'Tiang Galvanis 6M Tanpa Sambungan',
    type: QCType.material,
    status: QCReportStatus.NEEDS_FOLLOW_UP,
    checkedByName: 'Yanuar Luthfi',
    checkedByNik: 'NIK-908271',
    date: DateTime.now().subtract(const Duration(hours: 5)),
    siteId: 'site-1',
    siteName: 'Gudang Material Utama',
    area: 'Sektor 4 - Area Utara',
    detailLocation: 'Gudang Utama B-1',
    formCode: 'TA-FR-048-010-03',
    finalConclusion: 'Perlu Perbaikan',
    workLocation: WorkLocation(
      siteName: 'Gudang Material Utama',
      area: 'Sektor 4 - Area Utara',
      segment: 'Gudang Utama B-1',
      isCustom: false,
    ),
    generalInfo: {
      'poNumber': 'PO-2026-092',
      'poDate': '2026-06-12',
      'doNumber': 'DO-889013',
      'vendorName': 'PT Global Galvanis',
      'materialId': 'MAT-GALV-6M',
      'arrivalVolume': '1 batch',
      'samplingVolume': '4',
      'brandName': 'Galva Metal',
      'warehouseLocation': 'Gudang Utama B-1',
      'stelVersion': 'STEL-L-019-2024',
      'qaExpiryDate': '2029-09-30',
      'tkdnNumber': 'TKDN-GALV-9901',
      'tkdnCertDate': '2025-03-10',
      'tkdnValue': '48.9',
    },
    checklistAnswers: [
      QCChecklistAnswer(
        itemId: 'tb-galv-1',
        value: 'Ada karat permukaan',
        status: QCResultStatus.fail,
        warningMessage: 'Kondisi tidak sesuai standar',
        issueNote: 'Ditemukan bercak karat permukaan pada ujung sambungan',
        photoPaths: ['https://images.unsplash.com/photo-1590069261209-f8e9b8642343?auto=format&fit=crop&w=150&q=80'],
        paramName: 'Lapisan anti karat / galvanis',
        standardText: 'Mulus bebas karat',
      ),
    ],
    photos: [],
    staffNote: 'Ditemukan karat ringan di ujung tiang. Perlu pelapisan ulang.',
    adminNote: 'Harap lakukan coating ulang anti karat.',
  ),

  // 4. Instalasi ONT (Pekerjaan - Approved/Selesai)
  QCReportModel(
    id: 'QC-PEK-2026-0041',
    title: 'Instalasi ONT',
    type: QCType.pekerjaan,
    status: QCReportStatus.APPROVED,
    checkedByName: 'Yanuar Luthfi',
    checkedByNik: 'NIK-908271',
    date: DateTime.now().subtract(const Duration(days: 1)),
    siteId: 'site-1',
    siteName: 'Gudang Material Utama',
    area: 'Q1 - Cikarang Site',
    detailLocation: 'Pelanggan R-01',
    formCode: 'PEK-ONT-01',
    finalConclusion: 'Selesai',
    workLocation: WorkLocation(
      siteName: 'Gudang Material Utama',
      area: 'Q1 - Cikarang Site',
      segment: 'Pelanggan R-01',
      isCustom: false,
    ),
    generalInfo: {
      'mitraName': 'CV Prima Mandiri',
      'workSegment': 'FTTH',
    },
    checklistAnswers: [
      QCChecklistAnswer(
        itemId: 'pek-ont-1',
        value: 'OK',
        status: QCResultStatus.pass,
        photoPaths: ['https://images.unsplash.com/photo-1581094288338-2314dddb7ecc?auto=format&fit=crop&w=150&q=80'],
        paramName: 'Pemasangan unit ONT',
        standardText: 'Terpasang kokoh di dinding',
      ),
    ],
    photos: [],
    staffNote: 'ONT terpasang rapi dan sinyal optik stabil.',
    adminNote: 'Selesai.',
  ),

  // 5. Penarikan Kabel Dropcore (Pekerjaan - Waiting/On Progress)
  QCReportModel(
    id: 'QC-PEK-2026-0042',
    title: 'Penarikan Kabel Dropcore',
    type: QCType.pekerjaan,
    status: QCReportStatus.SUBMITTED,
    checkedByName: 'Yanuar Luthfi',
    checkedByNik: 'NIK-908271',
    date: DateTime.now().subtract(const Duration(hours: 4)),
    siteId: 'site-1',
    siteName: 'Gudang Material Utama',
    area: 'Sekitar Cibadung',
    detailLocation: 'Pole BD-12',
    formCode: 'PEK-DROP-02',
    finalConclusion: 'On Progress',
    workLocation: WorkLocation(
      siteName: 'Gudang Material Utama',
      area: 'Sekitar Cibadung',
      segment: 'Pole BD-12',
      isCustom: false,
    ),
    generalInfo: {
      'mitraName': 'PT Tunas Global',
      'workSegment': 'Outside Plant',
    },
    checklistAnswers: [
      QCChecklistAnswer(
        itemId: 'pek-drop-1',
        value: 'Sedang ditarik',
        status: QCResultStatus.notFilled,
        photoPaths: [],
        paramName: 'Kabel terpasang di clamp ring',
        standardText: 'Clamp ring terikat kencang',
      ),
    ],
    photos: [],
    staffNote: 'Pekerjaan penarikan kabel dropcore masih berlangsung.',
    adminNote: 'Menunggu penyelesaian lapangan.',
  ),

  // 6. Pemasangan Tiang (Pekerjaan - NeedFollowUp/Perlu Perbaikan)
  QCReportModel(
    id: 'QC-PEK-2026-0043',
    title: 'Pemasangan Tiang',
    type: QCType.pekerjaan,
    status: QCReportStatus.NEEDS_FOLLOW_UP,
    checkedByName: 'Yanuar Luthfi',
    checkedByNik: 'NIK-908271',
    date: DateTime.now().subtract(const Duration(hours: 2)),
    siteId: 'site-1',
    siteName: 'Gudang Material Utama',
    area: 'Area Utara',
    detailLocation: 'Tiang Nomor 14 dekat gerbang',
    formCode: 'PEK-CONST-01',
    finalConclusion: 'Perlu Perbaikan',
    workLocation: WorkLocation(
      siteName: 'Gudang Material Utama',
      area: 'Area Utara',
      segment: 'Tiang Nomor 14 dekat gerbang',
      isCustom: false,
    ),
    generalInfo: {
      'mitraName': 'CV Jaya Konstruksi',
      'workSegment': 'Construction',
    },
    checklistAnswers: [
      QCChecklistAnswer(
        itemId: 'pek-const-1',
        value: 'Cor retak',
        status: QCResultStatus.fail,
        warningMessage: 'Cor retak kasar',
        issueNote: 'Permukaan semen cor retak besar',
        photoPaths: ['https://images.unsplash.com/photo-1590069261209-f8e9b8642343?auto=format&fit=crop&w=150&q=80'],
        paramName: 'Pengecoran base pondasi',
        standardText: 'Cor rapi kokoh',
      ),
    ],
    photos: [],
    staffNote: 'Pengecoran base pondasi semen retak kasar.',
    adminNote: 'Harap lakukan tambal sulam semen cor base pondasi.',
  ),
];
