import '../../shared/models/enums.dart';
import '../../shared/models/qc_material_template_model.dart';

final List<QCMaterialTemplate> dummyQCMaterialTemplates = [
  // 1. TIANG BESI 7 METER 3 SEGMEN
  QCMaterialTemplate(
    id: 'tiang_besi_7m_3_segmen',
    name: 'Tiang Besi 7 Meter 3 Segmen',
    code: 'TA-FR-048-010-01',
    description: 'Pemeriksaan Fisik Tiang Besi 7 Meter 3 Segmen',
    checklistItems: [
      QCChecklistItem(
        id: 'tb73-1',
        label: 'Kondisi fisik luar baik/tidak cacat',
        category: 'Fisik',
        inputType: QCInputType.booleanCheck,
        standardText: 'OK',
        required: true,
        requiredPhoto: true,
        validationRule: QCValidationRule(
          type: QCValidationType.booleanRequired,
          warningInvalid: 'Fisik tiang tidak boleh cacat/bengkok',
        ),
      ),
      QCChecklistItem(
        id: 'tb73-2',
        label: 'Panjang total',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '7000 ± 40 mm',
        required: true,
        requiredPhoto: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 6960,
          maxValue: 7040,
          warningBelow: 'kurang dari standar',
          warningAbove: 'melebihi standar',
        ),
      ),
      QCChecklistItem(
        id: 'tb73-3',
        label: 'Panjang ruas tiang bagian atas',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '1370 ± 20 mm',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 1350,
          maxValue: 1390,
          warningBelow: 'kurang dari standar',
          warningAbove: 'melebihi standar',
        ),
      ),
      QCChecklistItem(
        id: 'tb73-4',
        label: 'Panjang ruas tiang bagian tengah',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '1570 ± 20 mm',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 1550,
          maxValue: 1590,
          warningBelow: 'kurang dari standar',
          warningAbove: 'melebihi standar',
        ),
      ),
      QCChecklistItem(
        id: 'tb73-5',
        label: 'Panjang ruas tiang bagian bawah',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '4260 ± 20 mm',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 4240,
          maxValue: 4280,
          warningBelow: 'kurang dari standar',
          warningAbove: 'melebihi standar',
        ),
      ),
      QCChecklistItem(
        id: 'tb73-6',
        label: 'Panjang Lakop',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'cm',
        standardText: '≥ 40 cm',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.min,
          minValue: 40,
          warningBelow: 'kurang dari standar',
        ),
      ),
      QCChecklistItem(
        id: 'tb73-7',
        label: 'Tebal Lakop',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '≥ 3 mm',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.min,
          minValue: 3,
          warningBelow: 'kurang dari standar',
        ),
      ),
      QCChecklistItem(
        id: 'tb73-8',
        label: 'Diameter luar ruas atas',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '76,3 ± 2 mm',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 74.3,
          maxValue: 78.3,
          warningBelow: 'kurang dari standar',
          warningAbove: 'melebihi standar',
        ),
      ),
      QCChecklistItem(
        id: 'tb73-9',
        label: 'Diameter luar ruas tengah',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '114 ± 2,9 mm',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 111.1,
          maxValue: 116.9,
          warningBelow: 'kurang dari standar',
          warningAbove: 'melebihi standar',
        ),
      ),
      QCChecklistItem(
        id: 'tb73-10',
        label: 'Diameter luar ruas bawah',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '139,8 ± 3,5 mm',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 136.3,
          maxValue: 143.3,
          warningBelow: 'kurang dari standar',
          warningAbove: 'melebihi standar',
        ),
      ),
      QCChecklistItem(
        id: 'tb73-11',
        label: 'Tebal tiang ruas atas',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '4 mm +15% -12,5%',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 3.5,
          maxValue: 4.6,
          warningBelow: 'kurang dari standar',
          warningAbove: 'melebihi standar',
        ),
      ),
      QCChecklistItem(
        id: 'tb73-12',
        label: 'Tebal tiang ruas tengah',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '4 mm +15% -12,5%',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 3.5,
          maxValue: 4.6,
          warningBelow: 'kurang dari standar',
          warningAbove: 'melebihi standar',
        ),
      ),
      QCChecklistItem(
        id: 'tb73-13',
        label: 'Tebal tiang ruas bawah',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '4 mm +15% -12,5%',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 3.5,
          maxValue: 4.6,
          warningBelow: 'kurang dari standar',
          warningAbove: 'melebihi standar',
        ),
      ),
      QCChecklistItem(
        id: 'tb73-14',
        label: 'Berat tiang minimal termasuk tutup',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'kg',
        standardText: '≥ 71,4 kg',
        required: true,
        requiredPhoto: true,
        validationRule: QCValidationRule(
          type: QCValidationType.min,
          minValue: 71.4,
          warningBelow: 'kurang dari standar',
        ),
      ),
      QCChecklistItem(
        id: 'tb73-15',
        label: 'Kerapian pengelasan pada sambungan',
        category: 'Fisik',
        inputType: QCInputType.booleanCheck,
        standardText: 'wajib sesuai',
        required: true,
        requiredPhoto: true,
        validationRule: QCValidationRule(
          type: QCValidationType.booleanRequired,
          warningInvalid: 'Pengelasan harus rapi',
        ),
      ),
      QCChecklistItem(
        id: 'tb73-16',
        label: 'Terdapat tanda tanam',
        category: 'Fisik',
        inputType: QCInputType.booleanCheck,
        standardText: 'Ada',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.booleanRequired,
        ),
      ),
      QCChecklistItem(
        id: 'tb73-17',
        label: 'Pengecatan sesuai standar',
        category: 'Fisik',
        inputType: QCInputType.choice,
        choices: ['Sesuai', 'Tidak Sesuai'],
        standardText: 'meni/hitam/cat identitas operator',
        required: true,
      ),
      QCChecklistItem(
        id: 'tb73-18',
        label: 'Terdapat nama atau simbol merk',
        category: 'Fisik',
        inputType: QCInputType.booleanCheck,
        standardText: 'Ada',
        required: true,
      ),
      QCChecklistItem(
        id: 'tb73-19',
        label: 'Timbul jelas pada tutup atas',
        category: 'Fisik',
        inputType: QCInputType.booleanCheck,
        standardText: 'Ada',
        required: true,
      ),
    ],
  ),

  // 2. TIANG BESI 9 METER 3 SEGMEN
  QCMaterialTemplate(
    id: 'tiang_besi_9m_3_segmen',
    name: 'Tiang Besi 9 Meter 3 Segmen',
    code: 'TA-FR-048-010-05',
    description: 'Pemeriksaan Fisik Tiang Besi 9 Meter 3 Segmen',
    checklistItems: [
      QCChecklistItem(
        id: 'tb93-1',
        label: 'Kondisi fisik luar baik/tidak cacat',
        category: 'Fisik',
        inputType: QCInputType.booleanCheck,
        standardText: 'OK',
        required: true,
        requiredPhoto: true,
        validationRule: QCValidationRule(type: QCValidationType.booleanRequired),
      ),
      QCChecklistItem(
        id: 'tb93-2',
        label: 'Panjang total',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '9000 ± 40 mm',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 8960,
          maxValue: 9040,
          warningBelow: 'kurang dari standar',
          warningAbove: 'melebihi standar',
        ),
      ),
      QCChecklistItem(
        id: 'tb93-3',
        label: 'Panjang ruas tiang bagian atas',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '2000 ± 20 mm',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 1980,
          maxValue: 2020,
          warningBelow: 'kurang dari standar',
          warningAbove: 'melebihi standar',
        ),
      ),
      QCChecklistItem(
        id: 'tb93-4',
        label: 'Panjang ruas tiang bagian tengah',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '2000 ± 20 mm',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 1980,
          maxValue: 2020,
          warningBelow: 'kurang dari standar',
          warningAbove: 'melebihi standar',
        ),
      ),
      QCChecklistItem(
        id: 'tb93-5',
        label: 'Panjang ruas tiang bagian bawah',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '5000 ± 20 mm',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 4980,
          maxValue: 5020,
          warningBelow: 'kurang dari standar',
          warningAbove: 'melebihi standar',
        ),
      ),
      QCChecklistItem(
        id: 'tb93-6',
        label: 'Panjang Lakop',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'cm',
        standardText: '40 cm',
        required: true,
        validationRule: QCValidationRule(type: QCValidationType.min, minValue: 40),
      ),
      QCChecklistItem(
        id: 'tb93-7',
        label: 'Tebal Lakop',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '3 mm',
        required: true,
        validationRule: QCValidationRule(type: QCValidationType.min, minValue: 3),
      ),
      QCChecklistItem(
        id: 'tb93-8',
        label: 'Diameter luar ruas atas',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '76,3 ± 2 mm',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 74.3,
          maxValue: 78.3,
          warningBelow: 'kurang dari standar',
          warningAbove: 'melebihi standar',
        ),
      ),
      QCChecklistItem(
        id: 'tb93-9',
        label: 'Diameter luar ruas tengah',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '114,3 ± 2,9 mm',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 111.4,
          maxValue: 117.2,
          warningBelow: 'kurang dari standar',
          warningAbove: 'melebihi standar',
        ),
      ),
      QCChecklistItem(
        id: 'tb93-10',
        label: 'Diameter luar ruas bawah',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '139,8 ± 3,5 mm',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 136.3,
          maxValue: 143.3,
          warningBelow: 'kurang dari standar',
          warningAbove: 'melebihi standar',
        ),
      ),
      QCChecklistItem(
        id: 'tb93-11',
        label: 'Tebal tiang ruas atas',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '4 mm +15% -12,5%',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 3.5,
          maxValue: 4.6,
        ),
      ),
      QCChecklistItem(
        id: 'tb93-12',
        label: 'Tebal tiang ruas tengah',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '4 mm +15% -12,5%',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 3.5,
          maxValue: 4.6,
        ),
      ),
      QCChecklistItem(
        id: 'tb93-13',
        label: 'Tebal tiang ruas bawah',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '5 mm +15% -12,5%',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 4.375,
          maxValue: 5.75,
        ),
      ),
      QCChecklistItem(
        id: 'tb93-14',
        label: 'Berat tiang minimal',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'kg',
        standardText: '120 kg',
        required: true,
        requiredPhoto: true,
        validationRule: QCValidationRule(type: QCValidationType.min, minValue: 120),
      ),
      QCChecklistItem(
        id: 'tb93-15',
        label: 'Kerapian pengelasan pada sambungan',
        category: 'Fisik',
        inputType: QCInputType.booleanCheck,
        standardText: 'OK',
        required: true,
      ),
      QCChecklistItem(
        id: 'tb93-16',
        label: 'Terdapat tanda tanam',
        category: 'Fisik',
        inputType: QCInputType.booleanCheck,
        standardText: 'Ada',
        required: true,
      ),
      QCChecklistItem(
        id: 'tb93-17',
        label: 'Pengecatan sesuai standar',
        category: 'Fisik',
        inputType: QCInputType.choice,
        choices: ['Sesuai', 'Tidak Sesuai'],
        standardText: 'Sesuai',
        required: true,
      ),
      QCChecklistItem(
        id: 'tb93-18',
        label: 'Terdapat nama atau simbol merk',
        category: 'Fisik',
        inputType: QCInputType.booleanCheck,
        standardText: 'Ada',
        required: true,
      ),
      QCChecklistItem(
        id: 'tb93-19',
        label: 'Timbul jelas pada tutup bagian atas',
        category: 'Fisik',
        inputType: QCInputType.booleanCheck,
        standardText: 'Ada',
        required: true,
      ),
    ],
  ),

  // 3. TIANG 7 METER 2 SEGMEN
  QCMaterialTemplate(
    id: 'tiang_7m_2_segmen',
    name: 'Tiang 7 Meter 2 Segmen',
    code: 'TA-FR-048-010-02',
    description: 'Pemeriksaan Fisik Tiang 7 Meter 2 Segmen',
    checklistItems: [
      QCChecklistItem(
        id: 't72-1',
        label: 'Kondisi fisik luar baik/tidak cacat',
        category: 'Fisik',
        inputType: QCInputType.booleanCheck,
        standardText: 'OK',
        required: true,
        requiredPhoto: true,
        validationRule: QCValidationRule(type: QCValidationType.booleanRequired),
      ),
      QCChecklistItem(
        id: 't72-2',
        label: 'Panjang total',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '7000 ± 40 mm',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 6960,
          maxValue: 7040,
        ),
      ),
      QCChecklistItem(
        id: 't72-3',
        label: 'Panjang ruas tiang segmen atas',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '2740 ± 20 mm',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 2720,
          maxValue: 2760,
        ),
      ),
      QCChecklistItem(
        id: 't72-4',
        label: 'Panjang ruas tiang segmen bawah',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '4260 ± 20 mm',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 4240,
          maxValue: 4280,
        ),
      ),
      QCChecklistItem(
        id: 't72-5',
        label: 'Diameter luar tiang segmen atas',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '76,3 ± 25 mm',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 51.3,
          maxValue: 101.3,
        ),
      ),
      QCChecklistItem(
        id: 't72-6',
        label: 'Diameter luar tiang segmen bawah',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '114,3 ± 2,9 mm',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 111.4,
          maxValue: 117.2,
        ),
      ),
      QCChecklistItem(
        id: 't72-7',
        label: 'Tebal tiang segmen atas',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '2,9 mm +15% -12,5%',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 2.5375,
          maxValue: 3.335,
        ),
      ),
      QCChecklistItem(
        id: 't72-8',
        label: 'Tebal tiang segmen bawah',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '2,9 mm +15% -12,5%',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 2.5375,
          maxValue: 3.335,
        ),
      ),
      QCChecklistItem(
        id: 't72-9',
        label: 'Berat tiang minimal',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'kg',
        standardText: '≥ 52,5 kg',
        required: true,
        requiredPhoto: true,
        validationRule: QCValidationRule(type: QCValidationType.min, minValue: 52.5),
      ),
      QCChecklistItem(
        id: 't72-10',
        label: 'Tebal Lakop',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '≥ 3 mm',
        required: true,
        validationRule: QCValidationRule(type: QCValidationType.min, minValue: 3),
      ),
      QCChecklistItem(
        id: 't72-11',
        label: 'Panjang Lakop',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'cm',
        standardText: '≥ 40 cm',
        required: true,
        validationRule: QCValidationRule(type: QCValidationType.min, minValue: 40),
      ),
      QCChecklistItem(
        id: 't72-12',
        label: 'Kerapian pengelasan pada sambungan',
        category: 'Fisik',
        inputType: QCInputType.booleanCheck,
        standardText: 'OK',
        required: true,
      ),
      QCChecklistItem(
        id: 't72-13',
        label: 'Terdapat tanda tanam',
        category: 'Fisik',
        inputType: QCInputType.booleanCheck,
        standardText: 'Ada',
        required: true,
      ),
      QCChecklistItem(
        id: 't72-14',
        label: 'Standar pengecatan',
        category: 'Fisik',
        inputType: QCInputType.choice,
        choices: ['Sesuai', 'Tidak Sesuai'],
        standardText: 'Sesuai',
        required: true,
      ),
      QCChecklistItem(
        id: 't72-15',
        label: 'Nama/simbol merk pabrik tercetak jelas pada tutup atas',
        category: 'Fisik',
        inputType: QCInputType.booleanCheck,
        standardText: 'Ada',
        required: true,
      ),
    ],
  ),

  // 4. TIANG GALVANIS 6M TANPA SAMBUNGAN
  QCMaterialTemplate(
    id: 'tiang_galvanis_6m_tanpa_sambungan',
    name: 'Tiang Galvanis 6M Tanpa Sambungan',
    code: 'TA-FR-048-010-03',
    description: 'Pemeriksaan Fisik Tiang Galvanis 6M Tanpa Sambungan',
    checklistItems: [
      QCChecklistItem(
        id: 'tg6-1',
        label: 'Kondisi fisik luar baik/tidak cacat',
        category: 'Fisik',
        inputType: QCInputType.booleanCheck,
        standardText: 'tidak cacat',
        required: true,
        requiredPhoto: true,
        validationRule: QCValidationRule(type: QCValidationType.booleanRequired),
      ),
      QCChecklistItem(
        id: 'tg6-2',
        label: 'Panjang total',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '6000 ± 50 mm',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 5950,
          maxValue: 6050,
        ),
      ),
      QCChecklistItem(
        id: 'tg6-3',
        label: 'Diameter luar',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '76,3 mm ± 1%',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 75.537,
          maxValue: 77.063,
        ),
      ),
      QCChecklistItem(
        id: 'tg6-4',
        label: 'Tebal tiang',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '4 mm +15% -12,2%',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 3.512,
          maxValue: 4.6,
        ),
      ),
      QCChecklistItem(
        id: 'tg6-5',
        label: 'Berat',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'kg',
        standardText: 'Minimal 43,78 kg',
        required: true,
        requiredPhoto: true,
        validationRule: QCValidationRule(type: QCValidationType.min, minValue: 43.78),
      ),
      QCChecklistItem(
        id: 'tg6-6',
        label: 'Terdapat tanda tanam',
        category: 'Fisik',
        inputType: QCInputType.booleanCheck,
        standardText: 'Ada',
        required: true,
      ),
      QCChecklistItem(
        id: 'tg6-7',
        label: 'Warna cat sesuai standar pengecatan',
        category: 'Fisik',
        inputType: QCInputType.choice,
        choices: ['Sesuai', 'Tidak Sesuai'],
        standardText: 'silver / cat identitas operator',
        required: true,
      ),
      QCChecklistItem(
        id: 'tg6-8',
        label: 'Terdapat nama atau simbol merk pabrik tercetak jelas pada tutup atas',
        category: 'Fisik',
        inputType: QCInputType.booleanCheck,
        standardText: 'Ada',
        required: true,
      ),
    ],
  ),

  // 5. TIANG BETON 7 METER
  QCMaterialTemplate(
    id: 'tiang_beton_7m',
    name: 'Tiang Beton 7 Meter',
    code: 'TA-FR-048-010-04',
    description: 'Pemeriksaan Fisik Tiang Beton 7 Meter',
    checklistItems: [
      QCChecklistItem(
        id: 'tb7-1',
        label: 'Kondisi fisik baik/tidak cacat',
        category: 'Fisik',
        inputType: QCInputType.booleanCheck,
        standardText: 'tidak terdapat retakan dan permukaan licin',
        required: true,
        requiredPhoto: true,
        validationRule: QCValidationRule(type: QCValidationType.booleanRequired),
      ),
      QCChecklistItem(
        id: 'tb7-2',
        label: 'Terdapat 3 lubang tembus',
        category: 'Fisik',
        inputType: QCInputType.booleanCheck,
        standardText: 'Ada',
        required: true,
      ),
      QCChecklistItem(
        id: 'tb7-3',
        label: 'Jarak tutup atas ke lubang tembus atas',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'm',
        standardText: '≥ 0,25 m',
        required: true,
        validationRule: QCValidationRule(type: QCValidationType.min, minValue: 0.25),
      ),
      QCChecklistItem(
        id: 'tb7-4',
        label: 'Jarak lubang tembus atas ke lubang tembus tengah',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'm',
        standardText: '≥ 0,35 m',
        required: true,
        validationRule: QCValidationRule(type: QCValidationType.min, minValue: 0.35),
      ),
      QCChecklistItem(
        id: 'tb7-5',
        label: 'Jarak lubang tembus tengah ke lubang tembus bawah',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'm',
        standardText: '≥ 0,35 m',
        required: true,
        validationRule: QCValidationRule(type: QCValidationType.min, minValue: 0.35),
      ),
      QCChecklistItem(
        id: 'tb7-6',
        label: 'Panjang total',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'm',
        standardText: '≥ 7 m',
        required: true,
        validationRule: QCValidationRule(type: QCValidationType.min, minValue: 7),
      ),
      QCChecklistItem(
        id: 'tb7-7',
        label: 'Diameter ruas atas',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '122 - 128 mm',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 122,
          maxValue: 128,
        ),
      ),
      QCChecklistItem(
        id: 'tb7-8',
        label: 'Diameter ruas bawah',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '200 - 206 mm',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 200,
          maxValue: 206,
        ),
      ),
      QCChecklistItem(
        id: 'tb7-9',
        label: 'Keterangan',
        category: 'Teks',
        inputType: QCInputType.text,
        standardText: 'Opsional',
        required: false,
      ),
      QCChecklistItem(
        id: 'tb7-10',
        label: 'Terdapat kode produksi / nomor seri',
        category: 'Fisik',
        inputType: QCInputType.booleanCheck,
        standardText: 'Ada',
        required: true,
        requiredPhoto: true,
      ),
      QCChecklistItem(
        id: 'tb7-11',
        label: 'Terdapat nama atau simbol merk pabrik pembuat',
        category: 'Fisik',
        inputType: QCInputType.booleanCheck,
        standardText: 'Ada',
        required: true,
      ),
      QCChecklistItem(
        id: 'tb7-12',
        label: 'Terdapat garis tanah ground line pada titik tumpu',
        category: 'Fisik',
        inputType: QCInputType.booleanCheck,
        standardText: 'Ada',
        required: true,
        requiredPhoto: true,
      ),
    ],
  ),

  // 6. TIANG BETON 9 METER
  QCMaterialTemplate(
    id: 'tiang_beton_9m',
    name: 'Tiang Beton 9 Meter',
    code: 'TA-FR-048-010-06',
    description: 'Pemeriksaan Fisik Tiang Beton 9 Meter',
    checklistItems: [
      QCChecklistItem(
        id: 'tb9-1',
        label: 'Kondisi fisik baik/tidak cacat',
        category: 'Fisik',
        inputType: QCInputType.booleanCheck,
        standardText: 'tidak terdapat retakan dan permukaan licin',
        required: true,
        requiredPhoto: true,
        validationRule: QCValidationRule(type: QCValidationType.booleanRequired),
      ),
      QCChecklistItem(
        id: 'tb9-2',
        label: 'Terdapat 6 lubang tembus',
        category: 'Fisik',
        inputType: QCInputType.booleanCheck,
        standardText: 'Ada',
        required: true,
      ),
      QCChecklistItem(
        id: 'tb9-3',
        label: 'Jarak tutup atas ke lubang tembus 1',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'm',
        standardText: '0,25 m',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.exact,
          exactValue: 0.25,
        ),
      ),
      QCChecklistItem(
        id: 'tb9-4',
        label: 'Jarak lubang tembus 1 ke lubang tembus 2',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'm',
        standardText: '0,35 m',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.exact,
          exactValue: 0.35,
        ),
      ),
      QCChecklistItem(
        id: 'tb9-5',
        label: 'Jarak lubang tembus 2 ke lubang tembus 3',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'm',
        standardText: '0,55 m',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.exact,
          exactValue: 0.55,
        ),
      ),
      QCChecklistItem(
        id: 'tb9-6',
        label: 'Jarak lubang tembus 3 ke lubang tembus 4',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'm',
        standardText: '0,50 m',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.exact,
          exactValue: 0.50,
        ),
      ),
      QCChecklistItem(
        id: 'tb9-7',
        label: 'Jarak lubang tembus 4 ke lubang tembus 5',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'm',
        standardText: '0,50 m',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.exact,
          exactValue: 0.50,
        ),
      ),
      QCChecklistItem(
        id: 'tb9-8',
        label: 'Jarak lubang tembus 5 ke lubang tembus 6',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'm',
        standardText: '0,50 m',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.exact,
          exactValue: 0.50,
        ),
      ),
      QCChecklistItem(
        id: 'tb9-9',
        label: 'Panjang Total',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'm',
        standardText: '≥ 9 m',
        required: true,
        validationRule: QCValidationRule(type: QCValidationType.min, minValue: 9),
      ),
      QCChecklistItem(
        id: 'tb9-10',
        label: 'Diameter ruas atas',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '122 - 128 mm',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 122,
          maxValue: 128,
        ),
      ),
      QCChecklistItem(
        id: 'tb9-11',
        label: 'Diameter ruas bawah',
        category: 'Dimensi',
        inputType: QCInputType.number,
        unit: 'mm',
        standardText: '222 - 228 mm',
        required: true,
        validationRule: QCValidationRule(
          type: QCValidationType.range,
          minValue: 222,
          maxValue: 228,
        ),
      ),
      QCChecklistItem(
        id: 'tb9-12',
        label: 'Keterangan',
        category: 'Teks',
        inputType: QCInputType.text,
        standardText: 'Opsional',
        required: false,
      ),
      QCChecklistItem(
        id: 'tb9-13',
        label: 'Terdapat kode produksi / nomor seri',
        category: 'Fisik',
        inputType: QCInputType.booleanCheck,
        standardText: 'Ada',
        required: true,
        requiredPhoto: true,
      ),
      QCChecklistItem(
        id: 'tb9-14',
        label: 'Terdapat nama atau simbol merk pabrik pembuat',
        category: 'Fisik',
        inputType: QCInputType.booleanCheck,
        standardText: 'Ada',
        required: true,
      ),
      QCChecklistItem(
        id: 'tb9-15',
        label: 'Terdapat garis tanah ground line pada titik tumpu',
        category: 'Fisik',
        inputType: QCInputType.booleanCheck,
        standardText: 'Ada',
        required: true,
        requiredPhoto: true,
      ),
    ],
  ),
];
